export const projectData = [
    {
        image: '/work/1.png',
        category: 'next js',
        name: 'TestNix',
        description:
            'TestNix is a split testing SaaS tool for Next.js developers that also helps in monitoring impressions, clicks, and conversions.',
        link: 'https://testnix.vercel.app/',
        github: 'https://github.com/abhirupkumar/testnix-npm',
    },
    {
        image: '/work/2.png',
        category: 'next js',
        name: 'Pixelwear',
        description: "Pixelwear is an e-commerce website with easy hassle-free payments powered by Razorpay, cart functionality and user authentication using jsonwebtoken.",
        link: 'https://pixelwear.vercel.app',
        github: 'https://github.com/abhirupkumar/pixelwear',
    },
    {
        image: '/work/3.png',
        category: 'next js',
        name: 'DocWhisperer',
        description:
            'DocWhisperer is Chat With Pdf SaaS Application which used Openai API and Langchain for AI responses. Pinecone is used as the vector database.',
        link: 'https://docwhisperer.me',
        github: 'https://github.com/abhirupkumar/docwhisperer',
    },
    {
        image: '/work/5.jpg',
        category: 'React Native',
        name: 'Instant',
        description: "Instant is a real-time chatting application. Users can create and chat in Groups, send texts, images and even star messages. They can even reply to others messages.",
        link: 'https://expo.dev/@abhirup/Instant?serviceType=classic&distribution=expo-go',
        github: 'https://github.com/abhirupkumar/instantchatapp',
    },
    {
        image: '/work/4.jpg',
        category: 'React Native',
        name: 'Instagram Clone',
        description: "This Instagram Clone is build using React Native(Expo). Users can post any picture/gif and can even comment to theirs as well as other's post. They can even set their profile image and username.",
        link: 'https://expo.dev/@abhirup/Instagram-Clone-Published-At-Expo',
        github: 'https://github.com/abhirupkumar/Instagram-clone',
    },
    {
        image: '/work/6.png',
        category: 'next js',
        name: 'Netflix Clone',
        description: "Replicated responsive Netflix's UI, making it familiar and intuitive for users. Curated a vast collection of movies and TV shows across various genres for an immersive viewing",
        link: 'https://netflix-akb.vercel.app/',
        github: 'https://github.com/abhirupkumar/Netflix-Clone',
    },
    {
        image: '/work/8.png',
        category: 'react js',
        name: 'Crypto Tracker',
        description: 'Crypto Tracker tracks all the information regarding top 100 crypto currencies. It also gives live update about every cryptocurrency.',
        link: 'https://crypto-tracker-akb.netlify.app',
        github: 'https://github.com/abhirupkumar/Crypto-Tracker',
    },
    {
        image: '/work/7.png',
        category: 'next js',
        name: 'Linkedin Clone',
        description: 'This application is made using Next.js, Tailwind Css, Material UI, MongoDb, Firebase and some React Libraries. Users can post their articles as well as images.',
        link: 'https://linkedin-clone-mauve.vercel.app/',
        github: 'https://github.com/abhirupkumar/linkedin-clone',
    },
    {
        image: '/work/9.jpg',
        category: 'react native',
        name: 'Deliveroo Clone',
        description: 'This is a Food Ordering App where users can order any food item as per their desire from any restaurant they like. They can even see the details of the restaurant they are ordering food from.',
        link: 'https://expo.dev/@abhirup/deliveroo-clone-apk',
        github: 'https://github.com/abhirupkumar/deliveroo-clone',
    },
];